import type { Metadata } from "next";
import { inter } from "./fonts";
import { Providers } from "./providers";
import ConnectBar from '@/components/ConnectBar'
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>

        <Providers>
          <ConnectBar></ConnectBar>
          {children}
        </Providers>
      </body>
    </html>
  );
}
